export const OPEN_COLLECTION_MODAL = 'OPEN_COLLECTION_MODAL';
export const CLOSE_COLLECTION_MODAL = 'CLOSE_COLLECTION_MODAL';
export const UPDATE_COLLECTION_MODAL = 'UPDATE_COLLECTION_MODAL';
export const SELECT_COLLECTION = 'SELECT_COLLECTION';